# Generated by Django 4.2.3 on 2023-09-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="usuarios",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("senha", models.CharField(max_length=200)),
            ],
        ),
    ]
