# Generated by Django 4.2.3 on 2023-09-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0002_rename_usuarios_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="TCC",
            fields=[
                ("id_tcc", models.AutoField(primary_key=True, serialize=False)),
                ("nome_autores", models.CharField(max_length=255)),
                ("ano", models.IntegerField()),
                ("tema", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("curso_graduacao", models.CharField(max_length=255)),
                ("arquivo_tcc", models.FileField(upload_to="tccs/")),
            ],
        ),
    ]
